spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adielson
    username: user
    password: mudar@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true